name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2  # Updated to v2

      - name: Display TF State Bucket Name
        run: echo "TF_STATE_BUCKET_NAME: ${{ secrets.AWS_TF_STATE_BUCKET_NAME }}"

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET_NAME }}" -backend-config="region=us-east-1"
        working-directory: ./terraform  # Ensure this matches your Terraform folder location

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
          -var="region=us-east-1" \
          -var="public_key=${{ secrets.PUBLIC_SSH_KEY }}" \
          -var="private_key=${{ secrets.PRIVATE_SSH_KEY }}" \
          -var="key_name=deployer-key" \
          -out=PLAN
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve PLAN
        working-directory: ./terraform

